// Maps a free-text tool/tag name (as typed by the admin) to a recognized
// icon slug from the skillicons.dev icon set. Returns null for anything
// unrecognized, so the caller can fall back to a plain text pill instead.

const ICON_ALIASES: Record<string, string> = {
  nextjs: "nextjs",
  "next.js": "nextjs",
  next: "nextjs",
  react: "react",
  reactjs: "react",
  vuejs: "vuejs",
  vue: "vuejs",
  "vue.js": "vuejs",
  nodejs: "nodejs",
  node: "nodejs",
  "node.js": "nodejs",
  supabase: "supabase",
  sqlite: "sqlite",
  sqlite3: "sqlite",
  javascript: "js",
  js: "js",
  typescript: "ts",
  ts: "ts",
  html: "html",
  html5: "html",
  css: "css",
  css3: "css",
  tailwind: "tailwind",
  tailwindcss: "tailwind",
  git: "git",
  github: "github",
  docker: "docker",
  python: "python",
  php: "php",
  java: "java",
  mongodb: "mongodb",
  mongo: "mongodb",
  mysql: "mysql",
  postgres: "postgres",
  postgresql: "postgres",
  redis: "redis",
  graphql: "graphql",
  express: "express",
  expressjs: "express",
  nestjs: "nestjs",
  nest: "nestjs",
  angular: "angular",
  svelte: "svelte",
  flutter: "flutter",
  dart: "dart",
  kotlin: "kotlin",
  swift: "swift",
  figma: "figma",
  vscode: "vscode",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  firebase: "firebase",
  vercel: "vercel",
  netlify: "netlify",
  linux: "linux",
  bash: "bash",
  c: "c",
  "c++": "cpp",
  cpp: "cpp",
  "c#": "csharp",
  csharp: "csharp",
  dotnet: "dotnet",
  ".net": "dotnet",
  rust: "rust",
  go: "go",
  golang: "go",
  ruby: "ruby",
  rails: "rails",
  laravel: "laravel",
  wordpress: "wordpress",
  bootstrap: "bootstrap",
  sass: "sass",
  scss: "sass",
  webpack: "webpack",
  vite: "vite",
  jest: "jest",
  cypress: "cypress",
  npm: "npm",
  yarn: "yarn",
  pnpm: "pnpm",
  redux: "redux",
  threejs: "threejs",
  "three.js": "threejs",
  django: "django",
  flask: "flask",
  fastapi: "fastapi",
  kubernetes: "kubernetes",
  k8s: "kubernetes",
  jenkins: "jenkins",
  terraform: "terraform",
  nginx: "nginx",
  apache: "apache",
  prisma: "prisma",
  electron: "electron",
  androidstudio: "androidstudio",
  android: "androidstudio",
  apple: "apple",
  windows: "windows",
};

export function getTechIconUrl(rawName: string): string | null {
  const key = rawName.trim().toLowerCase().replace(/\s+/g, "");
  const slug = ICON_ALIASES[key];
  if (!slug) return null;
  return `https://skillicons.dev/icons?i=${slug}`;
}